services:
  decideai-api:
    image: brsktdev/decideai-api:main
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_HOST=decideai-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=decideai-redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    depends_on:
      - decideai-db
      - decideai-redis
    labels:
      caddy: api.decideai.app
      caddy.reverse_proxy: '{{upstreams 8080}}'
    networks:
      - caddy
      - internal

  decideai-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - decideai_db_data:/var/lib/postgresql/data
    networks:
      - internal

  decideai-redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - decideai_redis_data:/data
    networks:
      - internal

volumes:
  decideai_db_data:
  decideai_redis_data:

networks:
  caddy:
    external: true
  internal:
    driver: bridge
